package parsers;

import java.util.HashMap;
import java.util.Map;

public class ExpectedVersions {
    private Map<String, String> expectedVersions;

    public ExpectedVersions() {
        expectedVersions = new HashMap<String, String>();
        expectedVersions.put("idea", "15.0.1");
        expectedVersions.put("youtrack", "6.5");
        expectedVersions.put("spring", "4.2.2");
        expectedVersions.put("apache", "2.4.17");
        expectedVersions.put("debian", "8.2");
        expectedVersions.put("eclipse", "4.5.1");
        expectedVersions.put("git", "2.6.3");
        expectedVersions.put("javase", "8u65");
        expectedVersions.put("jenkins", "1.638");
        expectedVersions.put("mysql", "5.7");
        expectedVersions.put("netbeans", "8.0.2");
        expectedVersions.put("php", "5.6.15");
        expectedVersions.put("puppet", "4.2.0");
        expectedVersions.put("sublimetext", "2.0.2");
        expectedVersions.put("subversion", "1.9.2");
        expectedVersions.put("tomcat", "8.0.28");
        expectedVersions.put("junit", "4.12");
        expectedVersions.put("vagrant", "1.7.4");
        expectedVersions.put("extjs", "6.0.0");
        expectedVersions.put("maven", "3.3.3");
        expectedVersions.put("hibernate", "5.0.2");
        expectedVersions.put("javascript", "ECMAScript 6");
        expectedVersions.put("ubuntu", "15.10");
        expectedVersions.put("nginx", "1.9.6");
        expectedVersions.put("elasticsearch", "2.0.0");
        expectedVersions.put("logstash", "2.0.0");
        expectedVersions.put("kibana", "4.2.0");
        expectedVersions.put("logstashforwarder", "0.4.0");
        expectedVersions.put("openssl", "0.9.8");
        expectedVersions.put("openssh", "7.1");
        expectedVersions.put("zabbix", "2.4");
        expectedVersions.put("nagios", "4.1.1");
        expectedVersions.put("cobertura", "2.1.1");
        expectedVersions.put("gatling", "2.1.7");
        expectedVersions.put("scala", "2.11.7");
        expectedVersions.put("selenium", "2.48.2");
        expectedVersions.put("virtualbox", "5.0.10");
        expectedVersions.put("windows", "10.0.10240");
        expectedVersions.put("centos", "7.1");
        expectedVersions.put("fedora", "23");
        expectedVersions.put("proxmox", "4.0");
        expectedVersions.put("sqlite", "3.9.2");
        expectedVersions.put("grunt", "0.4.5");
        expectedVersions.put("emacs", "24.5");
        expectedVersions.put("python", "3.5.0");
        expectedVersions.put("vim", "7.4");
        expectedVersions.put("awesome", "3.5.6");
        expectedVersions.put("i3", "4.11");
        expectedVersions.put("linux", "4.3");
        expectedVersions.put("xfce", "4.12");
        expectedVersions.put("elasticdump", "0.16.0");
        expectedVersions.put("solr", "5.3.1");
        expectedVersions.put("jquery", "2.1.4");
        expectedVersions.put("nexus", "2.11");
        expectedVersions.put("googlechrome", "46.0");
        expectedVersions.put("firefox", "42.0");
        expectedVersions.put("gnomeshell", "3.19.1");
        expectedVersions.put("kde", "4.14.6");
        expectedVersions.put("docker", "1.9.0");
        expectedVersions.put("kali", "2.0");
        expectedVersions.put("visualstudio", "2015 RTM");
        expectedVersions.put("bower", "1.6.5");
        expectedVersions.put("angularjs", "1.4.7");
        expectedVersions.put("curator", "3.4.0");
        expectedVersions.put("coreos", "845.0.0");
        expectedVersions.put("safari", "9.0.1");
        expectedVersions.put("drupal", "7.41");
        expectedVersions.put("foreman", "1.9.3");
        expectedVersions.put("wordpress", "4.3");
        expectedVersions.put("internetexplorer", "11.0.24");
        expectedVersions.put("nmap", "6.49");
        expectedVersions.put("edge", "25.10586");
        expectedVersions.put("opera", "33.0");
        expectedVersions.put("postgresql", "9.4.5");
        expectedVersions.put("lighttpd", "1.4.37");
        expectedVersions.put("bootstrap", "3.3.5");
        expectedVersions.put("ruby", "2.2.3");
        expectedVersions.put("zsh", "5.1.1");
        expectedVersions.put("ansible", "1.9.4");
        expectedVersions.put("polymer", "1.2.1");
        expectedVersions.put("fail2ban", "0.9.3");
        expectedVersions.put("go", "1.5.1");
        expectedVersions.put("metasploit", "4.11.5");
        expectedVersions.put("varnish", "4.1.0");
        expectedVersions.put("perl", "5.22.0");
        expectedVersions.put("lxc", "1.0");
        expectedVersions.put("nessus", "6.5.2");
        expectedVersions.put("latex", "2015.10.01");
        expectedVersions.put("bash", "4.3");
        expectedVersions.put("react", "0.14.2");
        expectedVersions.put("lua", "5.3.1");
        expectedVersions.put("dart", "1.12");
        expectedVersions.put("backbone", "1.2.3");
        expectedVersions.put("naxsi", "0.54");
        expectedVersions.put("memcached", "1.4.24");
        expectedVersions.put("libreoffice", "5.0.3");
        expectedVersions.put("wireshark", "1.12.8");
        expectedVersions.put("audacity", "2.1.1");
        expectedVersions.put("chef", "12.5.1");
        expectedVersions.put("vaadin", "7.5.8");
        expectedVersions.put("kubernetes", "1.1.1");
        expectedVersions.put("abletonlive", "9.5");
        expectedVersions.put("openbox", "3.6.1");
        expectedVersions.put("mercurial", "3.6.1");
        expectedVersions.put("rancheros", "0.4.0");
        expectedVersions.put("openbsd", "5.8");
        expectedVersions.put("blender", "2.76b");
    }

    public Map<String, String> getExpectedVersions() {
        return expectedVersions;
    }
}
