package parsers;

import java.util.HashMap;
import java.util.Map;

public class ExpectedVersions {
    private Map<String, String> expectedVersions;

    public ExpectedVersions() {
        expectedVersions = new HashMap<String, String>();
        expectedVersions.put("idea", "15.0.1");
        expectedVersions.put("youtrack", "6.5");
        expectedVersions.put("spring", "4.2.6");
        expectedVersions.put("apache", "2.4.18");
        expectedVersions.put("debian", "8.3");
        expectedVersions.put("eclipse", "4.5.2");
        expectedVersions.put("git", "2.7.2");
        expectedVersions.put("javase", "8u73");
        expectedVersions.put("jenkins", "1.651");
        expectedVersions.put("mysql", "5.7");
        expectedVersions.put("netbeans", "8.1");
        expectedVersions.put("php", "7.0.4");
        expectedVersions.put("puppet", "4.3");
        expectedVersions.put("sublimetext", "3.3103");
        expectedVersions.put("subversion", "1.9.3");
        expectedVersions.put("tomcat", "8.0.32");
        expectedVersions.put("junit", "4.12");
        expectedVersions.put("vagrant", "1.8.1");
        expectedVersions.put("extjs", "6.0.0");
        expectedVersions.put("maven", "3.3.9");
        expectedVersions.put("hibernate", "5.1.0");
        expectedVersions.put("javascript", "ECMAScript 6");
        expectedVersions.put("ubuntu", "15.10");
        expectedVersions.put("nginx", "1.9.12");
        expectedVersions.put("elasticsearch", "2.2.0");
        expectedVersions.put("logstash", "2.2.2");
        expectedVersions.put("kibana", "4.4.1");
        expectedVersions.put("logstashforwarder", "0.4.0");
        expectedVersions.put("openssl", "1.0.1");
        expectedVersions.put("openssh", "7.2");
        expectedVersions.put("zabbix", "3.0");
        expectedVersions.put("nagios", "4.1.1");
        expectedVersions.put("cobertura", "2.1.1");
        expectedVersions.put("gatling", "2.1.7");
        expectedVersions.put("scala", "2.11.7");
        expectedVersions.put("selenium", "2.52.0");
        expectedVersions.put("virtualbox", "5.0.16");
        expectedVersions.put("windows", "10.0");
        expectedVersions.put("centos", "7.2");
        expectedVersions.put("fedora", "23");
        expectedVersions.put("proxmox", "4.1");
        expectedVersions.put("sqlite", "3.11.1");
        expectedVersions.put("grunt", "0.4.5");
        expectedVersions.put("emacs", "24.5");
        expectedVersions.put("python", "3.5.1");
        expectedVersions.put("vim", "7.4");
        expectedVersions.put("awesome", "3.5.8");
        expectedVersions.put("i3", "4.11");
        expectedVersions.put("linux", "4.4.4");
        expectedVersions.put("xfce", "4.12");
        expectedVersions.put("elasticdump", "1.1.0");
        expectedVersions.put("solr", "5.5.0");
        expectedVersions.put("jquery", "2.2.1");
        expectedVersions.put("nexus", "2.11");
        expectedVersions.put("googlechrome", "49.0");
        expectedVersions.put("firefox", "44.0.2");
        expectedVersions.put("gnomeshell", "3.19.4");
        expectedVersions.put("kde", "4.14.3");
        expectedVersions.put("docker", "1.10.0");
        expectedVersions.put("kali", "2016.1");
        expectedVersions.put("visualstudio", "2015 Update 1");
        expectedVersions.put("bower", "1.7.7");
        expectedVersions.put("angularjs", "1.5.0");
        expectedVersions.put("curator", "3.4.1");
        expectedVersions.put("coreos", "976.0.0");
        expectedVersions.put("safari", "9.0.3");
        expectedVersions.put("drupal", "8.0");
        expectedVersions.put("foreman", "1.10");
        expectedVersions.put("wordpress", "4.4");
        expectedVersions.put("internetexplorer", "11.0.28");
        expectedVersions.put("nmap", "7.01");
        expectedVersions.put("edge", "25.10586");
        expectedVersions.put("opera", "35.0");
        expectedVersions.put("postgresql", "9.5.1");
        expectedVersions.put("lighttpd", "1.4.39");
        expectedVersions.put("bootstrap", "3.3.6");
        expectedVersions.put("ruby", "2.3.0");
        expectedVersions.put("zsh", "5.2");
        expectedVersions.put("ansible", "2.0.1.0");
        expectedVersions.put("polymer", "1.3.1");
        expectedVersions.put("fail2ban", "0.9.3");
        expectedVersions.put("go", "1.6");
        expectedVersions.put("metasploit", "4.11.6");
        expectedVersions.put("varnish", "4.1.1");
        expectedVersions.put("perl", "5.22.1");
        expectedVersions.put("lxc", "1.0");
        expectedVersions.put("nessus", "6.5.6");
        expectedVersions.put("latex", "2015.10.01");
        expectedVersions.put("bash", "4.3");
        expectedVersions.put("react", "0.14.7");
        expectedVersions.put("lua", "5.3.2");
        expectedVersions.put("dart", "1.14.2");
        expectedVersions.put("backbone", "1.3.1");
        expectedVersions.put("naxsi", "0.54");
        expectedVersions.put("memcached", "1.4.25");
        expectedVersions.put("libreoffice", "5.1.0");
        expectedVersions.put("wireshark", "2.0.2");
        expectedVersions.put("audacity", "2.1.2");
        expectedVersions.put("chef", "12.5.1");
        expectedVersions.put("vaadin", "7.6.1");
        expectedVersions.put("kubernetes", "1.1.8");
        expectedVersions.put("abletonlive", "9.6");
        expectedVersions.put("openbox", "3.6.1");
        expectedVersions.put("mercurial", "3.7.2");
        expectedVersions.put("rancheros", "0.4.2");
        expectedVersions.put("openbsd", "5.9");
        expectedVersions.put("blender", "2.76b");
        expectedVersions.put("symfony", "3.0");
        expectedVersions.put("rabbitmq", "3.6.1");
        expectedVersions.put("celery", "3.1.21");
        expectedVersions.put("flower", "0.9.0");
    }

    public Map<String, String> getExpectedVersions() {
        return expectedVersions;
    }
}
